### ISSUE TITLE
App not working !

### ISSUE THREAD

**Issue by yogeshpaisode** [vladotesanovic/ui-grid-angular2#1]
I am getting warning  "WARNING: Tried to load angular more than once." while trying to run this application.

To run application , i did following steps.
1: npm install
2: npm start

No error was found but still my application is not working.

Please helps me regarding , as this is high level requirement from my project.

Thanx

**Comment by snehalatapimprale** [comment]
Same issue is also occurring with my installed project. Please suggest the solution.

**Comment by vladotesanovic** [comment]
Ok, newer version of angular and angular-cli changed something... i must align it with that

**Comment by snehalatapimprale** [comment]
Thanks for your quick reply , but the versions of angular and angular-cli are not changing.

**Comment by vladotesanovic** [comment]
It should work now!
